title: Dania Orfali
description: >
  Ph.D. student in Chemical and Biomolecular Engineering at New York University.
  <br><br>
  Researching CO2 electroreduction, pulsed electrochemistry, operando spectroscopy,
  catalyst activity, Bayesian optimization, machine learning, and experimental automation.
  <br><br>
  dania.alorfali [at] gmail.com
  <br>
  <a href="/pdf/dania-orfali-resume.pdf">CV</a> |
  <a href="https://www.linkedin.com/in/dania-orfali-9567b2189/">LinkedIn</a>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
